### ISSUE TITLE
UCF Crime Dataset

### ISSUE THREAD

**Issue by guruvishnuvardan** [harshtikuu/Abnormal_Event_Detection#26]
Hi @blackeagle01,

Can you please let me know, If I can use the same code, to train UCF CRIME dataset?

Thanks
Guru

**Comment by jaycelol10** [comment]
@guruvishnuvardan  Dude did it work ? if not can u please tell me which code did you have used ?

**Comment by guruvishnuvardan** [comment]
No @jaycelol10 - We didn't work on this usecase.

**Comment by jaycelol10** [comment]
@guruvishnuvardan  sorry for bothering, so you didn't even implemented code for dat dataset ? , iam working in my graduation project and need help

**Comment by guruvishnuvardan** [comment]
@jaycelol10 Yes. We didn't implement the code

**Comment by jaycelol10** [comment]
Ok than you
